version: '3.4'

services:
  
  discountdb: 
    container_name: discountdb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=razvoj.softvera.matf@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:\data\db
  
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    
  catalog.api:
    container_name: catalog.api
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://catalogdb:27017"
    depends_on: 
      - catalogdb
    ports:
      - "8000:80"
  
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on: 
      - basketdb
    ports:
      - "8001:80"
  