services:
  
  discountdb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4
  
  catalogdb:
    image: mongo
  
  basketdb:
    image: redis:alpine
  
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.api:
    image: discount.api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
  
  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
  rabbitmq:
    image: rabbitmq:management-alpine

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  mssql_data:
